name: Randomized GitHub Activity

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes
  workflow_dispatch:  # Allows manual triggering

jobs:
  commit-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 10  # Prevents long delays from causing cancellations

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Randomized Commit
        run: |
          # Reduced random delay to prevent workflow cancellations
          DELAY=$(( RANDOM % 600 ))  # Max wait time is now 10 minutes
          echo "Sleeping for $DELAY seconds to randomize commit time..."
          sleep $DELAY

          # Ensure a change is always made to activity_log.txt
          TIMESTAMP=$(date +%s)  # Unique timestamp
          echo "Last updated on $(date) - $TIMESTAMP" >> activity_log.txt

          # Ensure a change is always made to notes.txt
          echo "Auto-update on $(date)" >> notes.txt

          # Random commit messages
          MESSAGES=("Improved documentation" "Refactored some code" "Updated project files" "Minor bug fixes" "Optimized performance")
          COMMIT_MESSAGE=${MESSAGES[$RANDOM % ${#MESSAGES[@]}]}

      - name: Git operations
        run: |
          git config --global user.name "BL41N3Y"
          git config --global user.email "bl41n3y@gmail.com"

          # Ensure the latest changes are pulled
          git fetch origin master
          git reset --hard origin/master

          # Ensure changes are staged
          git add activity_log.txt notes.txt
          
          # Only commit if there are actual changes
          git diff --staged --quiet || git commit -m "$COMMIT_MESSAGE"
          
          # Push the commit
          git push --force
