name: Randomized GitHub Activity

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes
  workflow_dispatch:  # Allows manual triggering

jobs:
  commit-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Randomized Commit
        run: |
          # Random delay between 0 and 3600 seconds (1 hour)
          DELAY=$(( RANDOM % 3600 ))
          echo "Sleeping for $DELAY seconds to randomize commit time..."
          sleep $DELAY

          # Random commit messages
          MESSAGES=("Improved documentation" "Refactored some code" "Updated project files" "Minor bug fixes" "Optimized performance")
          COMMIT_MESSAGE=${MESSAGES[$RANDOM % ${#MESSAGES[@]}]}

          # Simulate real activity by modifying a file
          echo "Last updated on $(date)" >> activity_log.txt

          # Git operations
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add activity_log.txt
          git commit -m "$COMMIT_MESSAGE" || exit 0
          git push
