name: Randomized GitHub Activity

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes
  workflow_dispatch:  # Allows manual triggering

jobs:
  commit-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Randomized Commit
        run: |
          # Random delay between 0 and 3600 seconds (1 hour)
          DELAY=$(( RANDOM % 3600 ))
          echo "Sleeping for $DELAY seconds to randomize commit time..."
          sleep $DELAY

          # Random commit messages
          MESSAGES=("Improved documentation" "Refactored some code" "Updated project files" "Minor bug fixes" "Optimized performance")
          COMMIT_MESSAGE=${MESSAGES[$RANDOM % ${#MESSAGES[@]}]}

          # Ensure file changes are detected
          TIMESTAMP=$(date +%s)  # Unique timestamp
          echo "Last updated on $(date) - $TIMESTAMP" > activity_log.txt

      - name: Git operations
        run: |
          git config --global user.name "BL41N3Y"
          git config --global user.email "bl41n3y@gmail.com"

          # Stash any uncommitted changes
          git stash push -m "Auto-stash before pull" || echo "No changes to stash"

          # Pull latest changes from remote branch
          git pull --rebase origin master || git reset --hard origin/master

          # Apply the stashed changes (if any)
          git stash list | grep "Auto-stash before pull" && git stash pop || echo "No stash to apply"

          # Ensure changes are staged and committed
          git add activity_log.txt
          git diff --cached --quiet || git commit -m "$COMMIT_MESSAGE"
          git push --force
